# Generated by Django 4.1.3 on 2022-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_price_task_subtask_task_user_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default='2022-11-11', null=True),
        ),
    ]
